name: dharavikabhootv2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  video_player: ^2.9.3
  audioplayers: ^6.4.0
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/videos/
    - assets/music/

  fonts:
    - family: Variex
      fonts:
        - asset: assets/fonts/Variex.ttf
        # - asset: assets/fonts/CONSOLAB.TTF
        #   weight: 700
        # - asset: assets/fonts/consolai.ttf
        #   style: italic
        # - asset: assets/fonts/CONSOLA.TTF
        # - asset: assets/fonts/consolaz.ttf
        #   weight: 900
